name: Daily Website Visit

on:
workflow_dispatch: # 手动触发工作流
  schedule:
    - cron: '5 * * * *'  # 每天 8 点（UTC 时间）

jobs:
  visit_website:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run curl to visit website
        run: |
          curl -s -o /dev/null https://ys.vlmee.dpdns.org/api.php/timming/index.html?enforce=1&name=wujin
