name: Website Visit Workflow

on:
  workflow_dispatch:  # 允许手动触发工作流
  schedule:
    - cron: '*/10 * * * *'  # 每10分钟执行一次

jobs:
  visit_website:
    runs-on: ubuntu-latest
    
    steps:
      - name: Visit website
        run: |
          curl -s -o /dev/null https://ys.vlmee.dpdns.org/api.php/timming/index.html?enforce=1&name=wujin
